"""
CLI 入口 for v2.0.

Usage:
  python -m agents_chat.v2.main init [--data-dir DIR]
  python -m agents_chat.v2.main run-agent AGENT_ID [--cli mock|qwen|opencode] [--data-dir DIR]
  python -m agents_chat.v2.main run-scanner [--data-dir DIR]
  python -m agents_chat.v2.main run-scheduler [--data-dir DIR]
  python -m agents_chat.v2.main run-all [--data-dir DIR]    # dev only
  python -m agents_chat.v2.main post CHANNEL CONTENT         # helper, 用 'from' = god
  python -m agents_chat.v2.main status [TASK_ID]             # 看 state_board
  python -m agents_chat.v2.main tail CHANNEL [N]            # 看频道最后 N 条 (默认 10)
  python -m agents_chat.v2.main inbox AGENT_ID               # 看 agent 邮箱 pending
  python -m agents_chat.v2.main reset                        # 清空所有 data (危险)

默认 data_dir: ./data_v2 (可用 AGENTS_CHAT_DATA_DIR 环境变量覆盖)
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
from pathlib import Path
from typing import Optional

from .agent import Agent
from .cli.mock import MockCLI
from .cli.opencode import OpenCodeCLI
from .cli.qwen import QwenCLI
from .files.channel import Channel
from .files.mailbox import Mailbox
from .scanner import Scanner
from .scheduler import Scheduler
from .state_board import StateBoard


DEFAULT_DATA_DIR = "./data_v2"


def get_data_dir(args) -> Path:
    p = (getattr(args, "_data_dir", None)
         or getattr(args, "data_dir", None)
         or os.environ.get("AGENTS_CHAT_DATA_DIR")
         or DEFAULT_DATA_DIR)
    return Path(p).resolve()


def ensure_dirs(data_dir: Path):
    """建子目录."""
    for sub in ["channels", "mailboxes", "sessions", "locks"]:
        (data_dir / sub).mkdir(parents=True, exist_ok=True)


# ============================================================================
# Subcommands
# ============================================================================


def cmd_init(args):
    """初始化 data_dir."""
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    # 写 README
    readme = data_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            f"# agents-chat-channel v2.0 data\n\n"
            f"Generated by `python -m agents_chat.v2.main init` at {time.ctime()}\n\n"
            f"Layout:\n"
            f"  channels/     # JSONL 频道 (每行一条消息)\n"
            f"  mailboxes/    # JSON 邮箱 (每个 agent 一个文件)\n"
            f"  sessions/     # JSON session 索引 (local → remote)\n"
            f"  locks/        # 任务认领锁 (task_xxx.lock)\n"
            f"  state_board.json    # 全局任务状态板\n"
            f"  scanner_state.json  # Scanner 各频道 offset\n"
            f"  scheduler_state.json # Scheduler request_log\n"
        )
    # 默认频道
    (data_dir / "channels" / "general.jsonl").touch()
    # 主动建 state 文件 (StateBoard / Scanner / Scheduler 是懒加载, init 时主动建)
    StateBoard(data_dir / "state_board.json")
    (data_dir / "scanner_state.json").write_text('{"offsets": {}, "updated_at": ""}')
    (data_dir / "scheduler_state.json").write_text('{"request_log": {}, "updated_at": ""}')
    print(f"✓ Initialized: {data_dir}")
    print(f"  Layout: channels/ mailboxes/ sessions/ locks/")
    print(f"  State: state_board.json scanner_state.json scheduler_state.json")


def make_cli(cli_name: str, agent_id: str, data_dir: Path):
    """根据 cli name 构造 CLI 实例."""
    if cli_name == "mock":
        return MockCLI()
    elif cli_name == "opencode":
        return OpenCodeCLI()
    elif cli_name == "qwen":
        history_dir = data_dir / "qwen_history"
        history_dir.mkdir(parents=True, exist_ok=True)
        return QwenCLI(history_dir=history_dir)
    else:
        raise ValueError(f"unknown CLI: {cli_name}")


async def _run_agent_async(args):
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    cli = make_cli(args.cli, args.agent_id, data_dir)
    agent = Agent(
        agent_id=args.agent_id,
        cli=cli,
        data_dir=data_dir,
        capabilities=args.capabilities or [],
        poll_interval=args.poll_interval,
        default_channel=args.channel,
    )
    try:
        await agent.run()
    except KeyboardInterrupt:
        agent.stop()


def cmd_run_agent(args):
    asyncio.run(_run_agent_async(args))


async def _run_scanner_async(args):
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    s = Scanner(data_dir=data_dir, scan_interval=args.scan_interval)
    try:
        await s.run()
    except KeyboardInterrupt:
        s.stop()


def cmd_run_scanner(args):
    asyncio.run(_run_scanner_async(args))


async def _run_scheduler_async(args):
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    s = Scheduler(
        data_dir=data_dir,
        stale_ttl=args.stale_ttl,
        grace_period=args.grace_period,
        check_interval=args.check_interval,
    )
    try:
        await s.run()
    except KeyboardInterrupt:
        s.stop()


def cmd_run_scheduler(args):
    asyncio.run(_run_scheduler_async(args))


async def _run_all_async(args):
    """开发用: 一起跑 scanner + scheduler + 多个 agent (subprocess 或 task)."""
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    # 注册默认 agent mailboxes
    for aid in args.agents:
        mb = data_dir / "mailboxes" / f"{aid}.json"
        if not mb.exists():
            Mailbox(mb, aid)

    scanner = Scanner(data_dir=data_dir, scan_interval=1.0)
    scheduler = Scheduler(
        data_dir=data_dir, stale_ttl=60, grace_period=30, check_interval=15,
    )
    agents = []
    for aid in args.agents:
        cli = make_cli(args.cli, aid, data_dir)
        agents.append(Agent(
            agent_id=aid, cli=cli, data_dir=data_dir, poll_interval=2.0,
        ))

    tasks = [asyncio.create_task(scanner.run())]
    for a in agents:
        tasks.append(asyncio.create_task(a.run()))
    tasks.append(asyncio.create_task(scheduler.run()))

    print(f"[run-all] started: scanner + scheduler + {len(agents)} agent(s)")
    try:
        await asyncio.gather(*tasks)
    except KeyboardInterrupt:
        scanner.stop(); scheduler.stop()
        for a in agents: a.stop()
        await asyncio.gather(*tasks, return_exceptions=True)


def cmd_run_all(args):
    asyncio.run(_run_all_async(args))


def cmd_post(args):
    data_dir = get_data_dir(args)
    ensure_dirs(data_dir)
    ch = Channel(data_dir / "channels" / f"{args.channel}.jsonl", args.channel)
    # 自动从 content 提取 mentions
    from .agent import extract_mentions
    mentions = extract_mentions(args.content)
    # 自动检测 [TASK] 标记
    import re
    msg_type = "task_broadcast" if re.search(r"\[TASK", args.content, re.IGNORECASE) else "mention"
    msg_id = ch.append(
        from_=args.sender,
        content=args.content,
        type=msg_type,
        mentions=mentions,
    )
    print(f"✓ Posted: {msg_id}  (channel={args.channel}, mentions={mentions}, type={msg_type})")


def cmd_status(args):
    data_dir = get_data_dir(args)
    sb = StateBoard(data_dir / "state_board.json")
    if args.task_id:
        e = sb.get(args.task_id)
        if not e:
            print(f"task {args.task_id} not found")
            return
        print(json.dumps(e, ensure_ascii=False, indent=2))
    else:
        all_tasks = sb.list_all()
        if not all_tasks:
            print("(empty)")
            return
        for tid, e in all_tasks.items():
            print(
                f"  {tid:25s} {e.get('agent', '?'):15s} "
                f"progress={e.get('progress', 0):3d}  "
                f"hb={e.get('heartbeat', '?')[:19]}"
            )


def cmd_tail(args):
    data_dir = get_data_dir(args)
    ch = Channel(data_dir / "channels" / f"{args.channel}.jsonl", args.channel)
    msgs = ch.tail(args.n)
    if not msgs:
        print(f"(empty channel: {args.channel})")
        return
    for m in msgs:
        ts = m.get("ts", "")[:19]
        frm = m.get("from", "?")
        ctype = m.get("type", "?")
        content = m.get("content", "")[:200].replace("\n", " | ")
        print(f"  [{ts}] {frm:15s} ({ctype:12s}) {content}")


def cmd_inbox(args):
    data_dir = get_data_dir(args)
    mb = Mailbox(data_dir / "mailboxes" / f"{args.agent_id}.json", args.agent_id)
    pending = mb.peek()
    if not pending:
        print(f"(empty inbox: {args.agent_id})")
        return
    for m in pending:
        ts = m.get("ts", "")[:19]
        mtype = m.get("type", "?")
        content = m.get("content", "")[:200].replace("\n", " | ")
        print(f"  [{ts}] ({mtype:14s}) {content}")


def cmd_reset(args):
    """危险: 清空 data_dir."""
    data_dir = get_data_dir(args)
    if not data_dir.exists():
        print(f"data dir {data_dir} 不存在, 无事可做")
        return
    if not args.yes:
        resp = input(f"⚠️  确认清空 {data_dir}? (yes/no): ")
        if resp.strip().lower() != "yes":
            print("已取消")
            return
    import shutil
    shutil.rmtree(data_dir)
    print(f"✓ Reset: {data_dir} 已清空")


# ============================================================================
# argparse
# ============================================================================


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m agents_chat.v2.main",
        description="agents-chat-channel v2.0 CLI",
    )
    p.add_argument("--data-dir", default=None, help=f"data dir (default: {DEFAULT_DATA_DIR} 或 $AGENTS_CHAT_DATA_DIR)")
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_common(sp):
        sp.add_argument("--data-dir", default=None, dest="_data_dir", help="(同顶层)")

    # init
    sp = sub.add_parser("init", help="初始化 data_dir")
    add_common(sp)

    # run-agent
    sp = sub.add_parser("run-agent", help="跑一个 Agent 进程")
    add_common(sp)
    sp.add_argument("agent_id")
    sp.add_argument("--cli", default="mock", choices=["mock", "opencode", "qwen"])
    sp.add_argument("--capabilities", nargs="*", default=[])
    sp.add_argument("--poll-interval", type=float, default=2.0)
    sp.add_argument("--channel", default="general")

    # run-scanner
    sp = sub.add_parser("run-scanner", help="跑 Scanner 后台进程")
    add_common(sp)
    sp.add_argument("--scan-interval", type=float, default=1.0)

    # run-scheduler
    sp = sub.add_parser("run-scheduler", help="跑 Scheduler 后台进程")
    add_common(sp)
    sp.add_argument("--stale-ttl", type=int, default=300)
    sp.add_argument("--grace-period", type=int, default=60)
    sp.add_argument("--check-interval", type=float, default=30.0)

    # run-all (dev)
    sp = sub.add_parser("run-all", help="一起跑: scanner + scheduler + 多 agent")
    add_common(sp)
    sp.add_argument("--agents", nargs="+", default=["qwencode", "claude"])
    sp.add_argument("--cli", default="mock", choices=["mock", "opencode", "qwen"])

    # post
    sp = sub.add_parser("post", help="发消息到频道 (helper)")
    add_common(sp)
    sp.add_argument("channel")
    sp.add_argument("content")
    sp.add_argument("--sender", default="god")

    # status
    sp = sub.add_parser("status", help="看 state_board")
    add_common(sp)
    sp.add_argument("task_id", nargs="?", default=None)

    # tail
    sp = sub.add_parser("tail", help="看频道最后 N 条")
    add_common(sp)
    sp.add_argument("channel")
    sp.add_argument("--n", type=int, default=10)

    # inbox
    sp = sub.add_parser("inbox", help="看 agent 邮箱 pending")
    add_common(sp)
    sp.add_argument("agent_id")

    # reset
    sp = sub.add_parser("reset", help="⚠️  清空 data_dir")
    add_common(sp)
    sp.add_argument("--yes", action="store_true")

    return p


def main(argv: list[str] | None = None):
    parser = build_parser()
    args = parser.parse_args(argv)

    dispatch = {
        "init": cmd_init,
        "run-agent": cmd_run_agent,
        "run-scanner": cmd_run_scanner,
        "run-scheduler": cmd_run_scheduler,
        "run-all": cmd_run_all,
        "post": cmd_post,
        "status": cmd_status,
        "tail": cmd_tail,
        "inbox": cmd_inbox,
        "reset": cmd_reset,
    }
    dispatch[args.cmd](args)


if __name__ == "__main__":
    main()
