"""
Step-Isolated Workflow E2E 测试.

覆盖完整的 3-stage pipeline (research → write → publish):
  1. test_e2e_3_stage_pipeline — 全流程成功
  2. test_e2e_with_checks — checks 校验
  3. test_e2e_handoff — upstream → downstream 文件传递
  4. test_e2e_visualization — HTML report 生成
  5. test_e2e_cli_run  — CLI workflow run 真实跑
  6. test_e2e_timeout — stage 超时失败
  7. test_e2e_single_stage_retry — 单 stage 重跑
"""
from __future__ import annotations

import asyncio
import json
import sys
import time
from pathlib import Path

import pytest

from agents_chat.workflow import (
    WorkflowRunResult,
    WorkflowScheduler,
    render_workflow_html,
    load_workflow_from_string,
)


# =============================================================================
# E2E Pipeline YAML
# =============================================================================

E2E_WORKFLOW_YAML = """
name: e2e-test-pipeline
description: "端到端 3-stage pipeline (research → write → publish)"
stages:
  - id: research
    workers:
      - id: researcher
        cli: mock
        system_prompt: "你是 researcher, 收集资料并产出 JSON"
    deliverable:
      path: out/research.json
      min_size: 10
      checks:
        - '"findings"'
        - '"sources"'
        - type: min_keywords
          keywords: ["finding", "source", "data"]
          min_count: 2
    timeout: 10

  - id: write
    depends_on: [research]
    workers:
      - id: writer
        cli: mock
        system_prompt: "基于 upstream input 写报告"
    deliverable:
      path: out/report.md
      min_size: 20
      checks:
        - "## Summary"
        - "## Recommendations"
    timeout: 10

  - id: publish
    depends_on: [write]
    workers:
      - id: publisher
        cli: mock
        system_prompt: "格式化并输出最终文件"
    deliverable:
      path: out/final.md
      min_size: 30
      checks:
        - type: contains_all
          value: ["## Summary", "## Recommendations", "## 结论"]
    timeout: 10
"""

# =============================================================================
# Pre-written deliverables (模拟 worker 产出)
# =============================================================================

RESEARCH_OUTPUT = json.dumps({
    "findings": [
        {"topic": "AI safety", "confidence": 0.95},
        {"topic": "Agent orchestration", "confidence": 0.88},
    ],
    "sources": ["arxiv.org/2401.xxx", "openai.com/research"],
    "data": {"total_papers": 2, "keyword": "multi-agent"},
})

WRITE_OUTPUT = """## Summary

This report covers AI safety and agent orchestration approaches.

Key findings:
- AI safety is critical (95% confidence)
- Agent orchestration shows promising results (88% confidence)

## Recommendations

1. Implement guardrail systems for all agents
2. Use stage-isolated workflows for production pipelines
3. Monitor agent outputs continuously
"""

PUBLISH_OUTPUT = """## Summary

AI safety and agent orchestration are key areas for 2026.

## Recommendations

1. Deploy guardrail systems
2. Adopt stage-isolated workflows
3. Continuous monitoring

## 结论

Multi-agent systems require structured oversight. Stage isolation provides the best balance of flexibility and safety.

---

Generated by publisher agent.
"""


# =============================================================================
# Helpers
# =============================================================================


def init_data_v2(data_dir: Path) -> None:
    """初始化 data_v2 (跟 cmd_init 一致)."""
    for sub in ["channels", "mailboxes", "sessions", "locks", "logs"]:
        (data_dir / sub).mkdir(parents=True, exist_ok=True)
    (data_dir / "state_board.json").write_text(
        json.dumps({"tasks": {}, "updated_at": ""}, ensure_ascii=False, indent=2)
    )
    (data_dir / "channels" / "general.jsonl").touch()


def write_deliverable(data_dir: Path, rel_path: str, content: str) -> None:
    """写 deliverable 文件."""
    full_path = data_dir / rel_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(content, encoding="utf-8")


# =============================================================================
# E2E Tests
# =============================================================================


class TestE2E3StagePipeline:
    """完整的 3-stage pipeline 端到端测试."""

    @pytest.mark.asyncio
    async def test_full_success(self, tmp_path: Path):
        """3 stage 全部成功."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir)

        # 模拟 workers 产出
        async def mock_produce():
            # Stage research: 0.5s 后产出
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
            # Stage write: 2s 后产出
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
            # Stage publish: 2s 后产出
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        assert result.status == "success", f"failed_stage={result.failed_stage}"
        assert result.stage_states == {
            "research": "success",
            "write": "success",
            "publish": "success",
        }

    @pytest.mark.asyncio
    async def test_checks_validation(self, tmp_path: Path):
        """Checks 校验: research 产出含 'findings' + 'sources' + min_keywords."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        spec.stages[0].timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir)

        async def mock_produce():
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
            # 不产出后续 stage (只跑 research)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        assert result.status == "success"
        # Checks 被记录
        assert "research" in result.check_results
        assert "write" in result.check_results
        assert "publish" in result.check_results

    @pytest.mark.asyncio
    async def test_handoff_deliverable(self, tmp_path: Path):
        """Upstream deliverable 被复制到 downstream workspace."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir)

        async def mock_produce():
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        assert result.status == "success"

        # 验证 handoff: writer 的 workspace 里有 research 的 deliverable
        writer_input = data_dir / "workspaces" / "writer" / "stage_inputs" / "research.json"
        assert writer_input.exists(), f"handoff file not found: {writer_input}"
        content = json.loads(writer_input.read_text())
        assert "findings" in content
        assert "sources" in content

        # 验证 handoff: publisher 的 workspace 里有 write 的 deliverable
        publisher_input = data_dir / "workspaces" / "publisher" / "stage_inputs" / "write.json"
        assert publisher_input.exists(), f"handoff file not found: {publisher_input}"
        content = publisher_input.read_text()
        assert "## Summary" in content

    @pytest.mark.asyncio
    async def test_runs_persistence(self, tmp_path: Path):
        """Run 状态被持久化到 runs/<run_id>.json."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir)

        async def mock_produce():
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        assert result.status == "success"

        # 验证持久化文件
        run_file = data_dir / "runs" / f"{result.run_id}.json"
        assert run_file.exists()
        data = json.loads(run_file.read_text())
        assert data["status"] == "success"
        assert data["workflow_name"] == "e2e-test-pipeline"
        assert "stage_states" in data
        assert data["stage_states"]["research"] == "success"

    @pytest.mark.asyncio
    async def test_visualization(self, tmp_path: Path):
        """E2E pipeline → HTML 可视化作."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir)

        async def mock_produce():
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
            await asyncio.sleep(2.0)
            write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        assert result.status == "success"

        # 生成 HTML report
        html = render_workflow_html(spec, result=result)
        assert "📋 e2e-test-pipeline" in html
        assert "mermaid" in html
        assert "research" in html
        assert "write" in html
        assert "publish" in html
        assert "success" in html
        # 保存到文件
        output = tmp_path / "report.html"
        output.write_text(html)
        assert output.exists()
        assert output.stat().st_size > 1000

    @pytest.mark.asyncio
    async def test_timeout_failure(self, tmp_path: Path):
        """Stage 超时 → workflow 失败, failed_stage 记录."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 1  # 极短 timeout

        scheduler = WorkflowScheduler(spec, data_dir)

        # 不产出 deliverable → 全部 timeout
        result = await scheduler.run()

        assert result.status == "failed"
        assert result.failed_stage is not None  # research timeout
        # research 失败
        assert result.stage_states.get("research") == "failed"

    @pytest.mark.asyncio
    async def test_single_stage_retry(self, tmp_path: Path):
        """--single-stage 只跑一个 stage, 跳过其他."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        spec = load_workflow_from_string(E2E_WORKFLOW_YAML)
        for s in spec.stages:
            s.timeout = 5

        scheduler = WorkflowScheduler(spec, data_dir, single_stage="write")

        async def mock_produce():
            await asyncio.sleep(0.5)
            write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)

        scheduler_task = asyncio.create_task(scheduler.run())
        mock_task = asyncio.create_task(mock_produce())

        result = await scheduler_task
        if not mock_task.done():
            mock_task.cancel()

        # 只有 write 跑了
        assert "write" in result.stage_states
        assert result.stage_states.get("write") == "success"
        assert "research" not in result.stage_states


class TestE2ECLIRun:
    """CLI workflow run 真实跑 (含 deliverable 预写)."""

    def test_cli_e2e_success(self, tmp_path: Path):
        """CLI 跑完整 E2E pipeline (预写 deliverable)."""
        data_dir = tmp_path / "data_v2"
        init_data_v2(data_dir)

        # 写 pipeline YAML
        pipeline = tmp_path / "pipeline.yaml"
        pipeline.write_text(E2E_WORKFLOW_YAML)

        # 预写所有 deliverable
        write_deliverable(data_dir, "out/research.json", RESEARCH_OUTPUT)
        write_deliverable(data_dir, "out/report.md", WRITE_OUTPUT)
        write_deliverable(data_dir, "out/final.md", PUBLISH_OUTPUT)

        import io
        old_stdout, old_stderr = sys.stdout, sys.stderr
        sys.stdout = io.StringIO()
        sys.stderr = io.StringIO()
        exit_code = 0
        try:
            from agents_chat.infra.main import main
            main([
                "workflow", "run",
                str(pipeline),
                "--data-dir", str(data_dir),
            ])
        except SystemExit as e:
            exit_code = e.code or 0
        finally:
            out = sys.stdout.getvalue()
            err = sys.stderr.getvalue()
            sys.stdout = old_stdout
            sys.stderr = old_stderr

        # 验证
        assert exit_code == 0, f"CLI exit={exit_code}, err={err[:500]}"
        assert "Workflow: e2e-test-pipeline" in out
        assert "SUCCESS" in out
        # 持久化文件
        run_files = list((data_dir / "runs").glob("run-*.json"))
        assert len(run_files) == 1
        run_data = json.loads(run_files[0].read_text())
        assert run_data["status"] == "success"
